#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>

int positionToNumber(int position[2], int keypad[5][5]) {
  int x = position[0];
  int y = position[1];
  return keypad[y][x];
}

void move(int position[2], char direction, int keypad[5][5]) {
  int x = position[0];
  int y = position[1];
  int newPosition[2] = {position[0], position[1]};

  // need to handle this better
  int maxLen = 4;

  if (direction == 'L') {
    newPosition[0] = (int)fmax(x - 1, 0);
  } else if (direction == 'R') {
    newPosition[0] = (int)fmin(x + 1, maxLen);
  } else if (direction == 'U') {
    newPosition[1] = (int)fmax(y - 1, 0);
  } else if (direction == 'D') {
    newPosition[1] = (int)fmin(y + 1, maxLen);
  }
  // only update position if sensible
  if (positionToNumber(newPosition, keypad) > 0) {
    position[0] = newPosition[0];
    position[1] = newPosition[1];
  }
}

int main() {
  printf("Running Day 2 exercise\n");

  char PROBLEM_INPUT[] = "LLRRLLRLDDUURLLRDUUUDULUDLUULDRDDDULLLRDDLLLRRDDRRUDDURDURLRDDULRRRLLULLULLRUULDLDDDUUURRRRURURDUDLLRRLDLLRRDRDLLLDDRRLUDDLDDLRDRDRDDRUDDRUUURLDUDRRLULLLDRDRRDLLRRLDLDRRRRLURLLURLRDLLRUDDRLRDRRURLDULURDLUUDURLDRURDRDLULLLLDUDRLLURRLRURUURDRRRULLRULLDRRDDDULDURDRDDRDUDUDRURRRRUUURRDUUDUDDDLRRUUDDUUDDDUDLDRDLRDUULLRUUDRRRDURLDDDLDLUULUDLLRDUDDDDLDURRRDRLLRUUUUDRLULLUUDRLLRDLURLURUDURULUDULUDURUDDULDLDLRRUUDRDDDRLLRRRRLDRRRD\nDRRRDULLRURUDRLRDLRULRRLRLDLUDLUURUUURURULRLRUDRURRRLLUDRLLDUDULLUUDLLUUUDDRLRUDDDDLDDUUDULDRRRDULUULDULDRUUULRUDDDUDRRLRLUDDURLLDRLUDUDURUUDRLUURRLUUUDUURUDURLUUUDRDRRRDRDRULLUURURDLUULLDUULUUDULLLDURLUDRURULDLDLRDRLRLUURDDRLDDLRRURUDLUDDDLDRLULLDRLLLURULLUURLUDDURRDDLDDDDRDUUULURDLUUULRRLRDLDRDDDRLLRUDULRRRUDRRLDRRUULUDDLLDUDDRLRRDLDDULLLRDURRURLLULURRLUULULRDLULLUUULRRRLRUDLRUUDDRLLLLLLLURLDRRUURLDULDLDDRLLLRDLLLDLRUUDRURDRDLUULDDRLLRRURRDULLULURRDULRUDUDRLUUDDDDUULDDDUUDURLRUDDULDDDDRUULUUDLUDDRDRD\nRRRULLRULDRDLDUDRRDULLRLUUDLULLRUULULURDDDLLLULRURLLURUDLRDLURRRLRLDLLRRURUDLDLRULDDULLLUUDLDULLDRDLRUULDRLURRRRUDDLUDLDDRUDDUULLRLUUDLUDUDRLRUULURUDULDLUUDDRLLUUURRURUDDRURDLDRRDRULRRRRUUUDRDLUUDDDUDRLRLDRRRRUDDRLLRDRLUDRURDULUUURUULLRDUUULRULRULLRULRLUDUDDULURDDLLURRRULDRULDUUDDULDULDRLRUULDRDLDUDRDUDLURLLURRDLLDULLDRULDLLRDULLRURRDULUDLULRRUDDULRLDLDLLLDUDLURURRLUDRRURLDDURULDURRDUDUURURULLLUDDLDURURRURDDDRRDRURRUURRLDDLRRLDDULRLLLDDUDRULUULLULUULDRLURRRLRRRLDRRLULRLRLURDUULDDUDLLLUURRRLDLUDRLLLRRUU\nURLDDDLDRDDDURRRLURRRRLULURLDDUDRDUDDLURURLLRDURDDRLRUURLDLLRDLRUUURLRLDLDRUDDDULLDULLDUULURLDRDUDRRLRRLULRDDULUDULDULLULDLRRLRRLLULRULDLLDULRRLDURRRRDLURDLUDUUUDLURRRRRUDDUDUUDULDLURRDRLRLUDUDUUDULDDURUDDRDRUDLRRUDRULDULRDRLDRUDRLLRUUDDRLURURDRRLRURULLDUUDRDLULRUULUDURRULLRLUUUUUDULRLUUDRDUUULLULUDUDDLLRRLDURRDDDLUDLUUDULUUULDLLLLUUDURRUDUDLULDRRRULLLURDURDDLRRULURUDURULRDRULLRURURRUDUULRULUUDDUDDUURLRLURRRRDLULRRLDRRDURUDURULULLRUURLLDRDRURLLLUUURUUDDDLDURRLLUUUUURLLDUDLRURUUUDLRLRRLRLDURURRURLULDLRDLUDDULLDUDLULLUUUDLRLDUURRR\nRLLDRDURRUDULLURLRLLURUDDLULUULRRRDRLULDDRLUDRDURLUULDUDDDDDUDDDDLDUDRDRRLRLRLURDURRURDLURDURRUUULULLUURDLURDUURRDLDLDDUURDDURLDDDRUURLDURRURULURLRRLUDDUDDDLLULUDUUUDRULLLLULLRDDRDLRDRRDRRDLDLDDUURRRDDULRUUURUDRDDLRLRLRRDLDRDLLDRRDLLUULUDLLUDUUDRDLURRRRULDRDRUDULRLLLLRRULDLDUUUURLDULDDLLDDRLLURLUDULURRRUULURDRUDLRLLLRDDLULLDRURDDLLDUDRUDRLRRLULLDRRDULDLRDDRDUURDRRRLRDLDUDDDLLUDURRUUULLDRLUDLDRRRRDDDLLRRDUURURLRURRDUDUURRDRRUDRLURLUDDDLUDUDRDRURRDDDDRDLRUDRDRLLDULRURULULDRLRLRRLDURRRUL";

  // int KEYPAD[3][3] = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};  // For Part A
  int KEYPAD[5][5] = {
    {-999, -999, 1, -999, -999},
    {-999, 2, 3, 4, -999},
    {5, 6, 7, 8, 9},
    {-999, (int) 'A', (int) 'B', (int) 'C', -999},
    {-999, -999, (int) 'D', -999, -999}
  };   // For Part B

  size_t maxSize = 10;
  char * split[maxSize];
  char splitString[] = "\n";

  // split up input by newlines
  for (int i = 0; i < maxSize; i++) {
    if (i == 0) {
      split[i] = strtok(PROBLEM_INPUT, splitString);
    } else {
      split[i] = strtok(NULL, splitString);
      if (split[i] == NULL)
        break;
    }
  }

  // Go through each line following instructions
  // int POSITION[2] = {1, 1};  // For Part A
  int POSITION[2] = {0, 2};  // For Part B
  for (int i = 0; i < maxSize; i++) {
    char * stepStr = split[i];
    if (stepStr == NULL)
      break;
    int stepLen = strlen(stepStr);
    for (int j = 0; j < stepLen; j++) {
      move(POSITION, stepStr[j], KEYPAD);
    }
    int n = positionToNumber(POSITION, KEYPAD);
    // To handle printing of chars
    if (n < 10) {
      printf("%d\n", n);
    } else {
      printf("%c\n", n);
    }
  }

   return 0;
}